[package]
name = "Less"
version = "0.1.0"
edition = "2024"
build = "src/build.rs"

[build-dependencies]
winresource = "0.1.20"


[dependencies]
eframe = "*" 
egui = "*"
image = "0.25.6"
rfd = "0.15.3"
